add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$terraform\
$time\
$character"""

[directory]
truncation_length = 1



[character]
success_symbol = "[->](bold green)"
error_symbol = "[x](bold red) "

[hostname]
disabled = true

[username]
style_user = "red bold"
style_root = "red bold"
format = "[$user]($style) [at](bold green) "
disabled = false
show_always = true

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%R"
utc_time_offset = "+5:30"
time_range = "0:00:00-23:59:59"
